version: '3'
services:
  teamcity-server:
    container_name: teamcity-server
    image: jetbrains/teamcity-server:2018.1.5
    volumes:
      - ./.teamcity/data:/data/teamcity_server/datadir
      - ./.teamcity/logs:/opt/teamcity/logs
    ports:
      - 18111:8111
  
  teamcity-agent1:
    container_name: teamcity-agent1
    image: jetbrains/teamcity-agent:2018.1.5
    volumes:
      - ./.teamcity/agents/agent1:/data/teamcity_agent/conf
    environment:
      SERVER_URL: "http://teamcity-server:8111"
      AGENT_NAME: "agent1"
      DOCKER_IN_DOCKER: start
    privileged: true
    ports:
      - 8111:8111
